---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-tekton-dashboard
spec:
  params:
    - name: package
      description: package to release
      default: github.com/tektoncd/dashboard
    - name: gitRevision
      description: the git revision to release
      default: main
  workspaces:
    - name: source-repo
      description:
  steps:
    - name: build-static
      # yamllint disable rule:line-length
      # Because of long image coordinates and later in the Task when we get Node.js
      image: gcr.io/tekton-releases/tests/test-runner@sha256:a4a64b2b70f85a618bbbcc6c0b713b313b2e410504dee24c9f90ec6fe3ebf63f
      workingDir: /workspace/source-repo/git
      env:
        - name: GOPATH
          value: /workspace/go
      command: ["/bin/sh", "-ce"]
      args:
        - |
          set -e
          set -x
          pwd
          echo '=========='

          apt-get update
          apt-get install -y curl
          curl -O https://nodejs.org/dist/v14.15.0/node-v14.15.0-linux-x64.tar.xz
          tar xf node-v14.15.0-linux-x64.tar.xz
          export PATH=$PATH:$(pwd)/node-v14.15.0-linux-x64/bin
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=$PATH:$HOME/.npm-global/bin
          npm ci
          npm run bootstrap:ci
          npm run build_ko
