---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dashboard-report-bucket
spec:
  params:
    - name: releaseBucket
    - name: versionTag
  results:
    - name: release
      description: the URL of the release file
    - name: release-ro
      description: the URL of the readonly release file
    - name: openshift-release
      description: the URL of the OpenShift release file
    - name: openshift-release-ro
      description: the URL of the OpenShift readonly release file
  steps:
    - name: create-results
      image: alpine
      script: |
        release-bucket=$(params.releaseBucket)
        BASE_URL=$(echo "${release-bucket}/previous/$(params.versionTag)")
        # If the bucket is in the gs://
        # return the corresponding public https URL
        BASE_URL=$(echo ${BASE_URL} | \
          sed 's,gs://,https://storage.googleapis.com/,g')
        echo "${BASE_URL}/tekton-dashboard-release.yaml" > \
              $(results.release.path)
        echo "${BASE_URL}/tekton-dashboard-release-readonly.yaml" > \
              $(results.release-ro.path)
        echo "${BASE_URL}/openshift-tekton-dashboard-release.yaml" > \
              $(results.openshift-release.path)
        echo "${BASE_URL}/openshift-tekton-dashboard-release-readonly.yaml" > \
              $(results.openshift-release-ro.path)
